=== curso-manejo-archivos/agenda-xml/src/agendaxml/agenda.dtd
<?xml version='1.0' encoding='UTF-8'?>
<!--
    Un ejemplo para utilizar Ã©sta DTD en un XML

    <?xml version="1.0"?>

    <!DOCTYPE agenda SYSTEM "agenda.dtd">

    <agenda>
    ...
    </agenda>
-->

<!--- Agenda debe de estar compuesta por al menos un elemento persona -->
<!ELEMENT agenda (persona+)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT persona (nombres,apellidos,telefono,direccion)>
<!ATTLIST persona
    codigo ID #REQUIRED>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombres (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellidos (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT telefono (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT direccion (#PCDATA)>

=== curso-manejo-archivos/agenda-xml/src/agendaxml/agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (C) 2015 Dhaby Xiloj <dhabyx@gmail.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<!DOCTYPE agenda SYSTEM 'agenda.dtd'>

<agenda>
    <persona codigo="p1">
        <nombres>Juan</nombres>
        <apellidos>Perez</apellidos>
        <telefono>123456</telefono>
        <direccion>En alg√∫n lugar</direccion>
    </persona>
    <persona codigo="p2">
        <nombres>Pedro</nombres>
        <apellidos>Mendez</apellidos>
        <telefono>123456</telefono>
        <direccion>En su casa</direccion>
    </persona>
    <persona codigo="p3">
        <nombres>Fulano</nombres>
        <apellidos>Mendez</apellidos>
        <telefono>123456</telefono>
        <direccion>En su casa</direccion>
    </persona>
    <persona codigo="p4">
        <nombres>Mengano</nombres>
        <apellidos>Perez</apellidos>
        <telefono>123456</telefono>
        <direccion>En su casa</direccion>
    </persona>
</agenda>

=== curso-manejo-archivos/agenda-xml/src/agendaxml/agenda2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <persona codigo="p1">
        <nombres>Fulano</nombres>
        <apellidos>Perez</apellidos>
        <telefono>123423</telefono>
        <direccion>En alg√∫n lugar</direccion>
    </persona>
    <persona codigo="p2">
        <nombres>Mengano</nombres>
        <apellidos>Perez</apellidos>
        <telefono>987351</telefono>
        <direccion>En otro lugar</direccion>
    </persona>
</agenda>
